---
title: "GPT-Q"
output: github_document
---




## Packages

```{r}
# Install these packages if you don't have them yet
# if (!require("pacman")) install.packages("pacman")

pacman::p_load(tidyverse, rvest, tidybrowse, magrittr)

```


## Scrape Data

```{r, eval = F}
# First Container
chrome <- docker$new(
  image_src = "selenium/standalone-chrome-debug", #Image to be used (model for the container)
  container_name = "chrome",
  other_arguments = "-p 4446:4444 -p 4447:5900"
)

view_container("chrome") #Since we have not yet initialized any browser, we do not see anything, but the raw container/mini-computer.

chrome_driver <- get_driver(4446)

chrome_driver$open()

chrome_driver$navigate("https://qanon.pub/#142")

## store page
q <- chrome_driver$getPageSource() %>% 
  extract2(1) 

## save ot
saveRDS(q, file = "q.rds")
```

## Look at Trivia

```{r}
q <- readRDS(file = "q.rds")

q_trivia <- q %>% 
  read_html() %>% 
  html_nodes(".text") %>%
  as.character() %>%
  str_split("<br>") %>%
  unlist()

write_lines(q_trivia, path = "q_trivia.txt", sep = "\n")

q_trivia
```
